trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@1
  displayName: Build test image
  inputs:
    dockerComposeFile: 'test-docker-compose.yaml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'
    projectName: tests

- task: DockerCompose@1
  displayName: Run tests
  inputs:
    dockerComposeFile: 'test-docker-compose.yaml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'
    arguments: '--abort-on-container-exit'
    projectName: tests

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  condition: always()
  inputs:
    summaryFileLocation: 'coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'test-results/test-results.xml'
    failTaskOnFailedTests: true
    failTaskOnMissingResultsFile: true